[build]
  publish = "public"
  command = "make build"

[dev]
  command = "hugo server -w"
  targetPort = 1313
  autoLaunch = true

[build.environment]
  HUGO_VERSION = "0.147.9"
  HUGO_ENV = "production"
  NODE_ENV = "production"

[context.preview.environment]
  HUGO_BASEURL = "https://preview--learnitmyway.netlify.com/"

[context.production.environment]
  HUGO_BASEURL = "https://learnitmyway.com/"